### ISSUE TITLE
Already implemented in i3?

### ISSUE THREAD

**Issue by javier-lopez** [alexrochas/i3-workspace-rollback#3]
Hello,

I'm not sure if I understood correctly the plugin functionality, if I did then I think this is [already implemented](https://i3wm.org/docs/userguide.html#_automatic_back_and_forth_when_switching_to_the_current_workspace) in i3 through the `workspace_auto_back_and_forth` option.

When enabled if I move between workspaces, eg: 1 -> 3 (Win+3) and then 3 -> 8 (Win + 8) if I press Win + 8 on this scenario I'll get back to the 3rd Workspace which was the last visited workspace.

If this plugin provides another functionality just ignore the comment :nerd_face:

**Comment by alexrochas** [comment]
Hi,

strange you say that, I didn't know this functionality was already in i3. Believe? =x
I did something a little different, added (at first) Mod4+z (or in future some configurable key) as trigger key.

And the implemented rollback is an stack so will rollback indefinitely, like an text editor. (I did't understand if i3 do this)

What do you think about? May be util? 
Thanks for reply. =)

**Comment by javier-lopez** [comment]
Ok, I got it, the `Mod4+z` shotcut makes sense now =), AFAIK i3 `workspace_auto_back_and_forth` option will only save the last workspace so you won't be able to move further in the history, so I think this plugin could be useful in setups where you've plenty of workspaces and they're not categorized.
